### ISSUE TITLE
I could not notify with Attachments / Block to Slack using this package.

### ISSUE THREAD

**Issue by psbss** [tokorom/action-slack-incoming-webhook#11]
Hello.

I could not notify with Attachments / Block to Slack.  
When I use Attachments like this, It will only appear as shown in the photo below.

```
...
- name: Slack Incoming Webhook
  if: success()
  uses: tokorom/action-slack-incoming-webhook@v1.1.3
  env:
    INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  with:
    text: This is test.
    attachments: |
      [
        {
          "color": "good",
          "author_name": "${{ github.actor }}",
          "author_icon": "${{ github.event.sender.avatar_url }}",
          "fields": [
            {
              "title": "GitHub Actions URL",
              "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
            }
          ]
        }
      ]
```
![2021-01-02_18h04_18](https://user-images.githubusercontent.com/24839924/103454198-f20c8400-4d24-11eb-83fe-63b60dd73d59.png)

---

Also, I use Block payload like this.  
I could not catch the notify.

```
# Slack notify
- name: Slack Incoming Webhook
  if: success()
  uses: tokorom/action-slack-incoming-webhook@v1.1.3
  env:
    INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  with:
    blocks: |
      [
        {
          "type": "section",
          "text": {
            "type": "plain_text",
            "text": "ブログの更新が完了したよ！",
            "emoji": true
          }
        },
        {
          "type": "divider"
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "image",
              "image_url": "${{ github.event.sender.avatar_url }}",
              "alt_text": "github avatar"
            },
            {
              "type": "mrkdwn",
              "text": ": ${{ github.actor }}"
            }
          ]
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "plain_text",
              "text": "Commit Message :",
              "emoji": true
            }
          ]
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "plain_text",
              "text": "GitHub Actions URL :"
            },
            {
              "type": "mrkdwn",
              "text": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
            }
          ]
        }
      ]
```

I want to solve problem because I want to use this package to notify my Slack.  
I have no idea to solve this problem. Plz give me an idea.

Thank you :)

**Comment by brettins** [comment]
I am experiencing the same issue. When I use attachments/blocks only the text message appears. 

```
     if: ${{ success() }}
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: ":heavy_check_mark: Build success - Deploy - Server - TEST - Azure Web Apps CI/CD. :heavy_check_mark:"
        attachments: |
          [
            {
              "color": "good",
              "fields": [
                {
                  "title": "Status",
                  "value": "Success!"
                },
                {
                  "title": "Stage",
                  "value": "test"
                },
                {
                  "title": "Application",
                  "value": "Backend NodeJS Server"
                },
                {
                  "title": "View Deploy Log",
                  "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                },
              ]
            }
          ]
```
output is:

![image](https://user-images.githubusercontent.com/5176335/103842405-1af98580-5053-11eb-9ac9-46bb5fb126dc.png)


With no block/attachments.

**Comment by tokorom** [comment]
@psbss @brettins 

Thanks for the report.

I tried copying and pasting the attachments and blocks you posted above as is, and both attachments and blocks are displayed in my environment.

I'm also wondering if there is any possibility that this could affect the Slack App settings, for example.

![スクリーンショット 2021-05-06 17 37 34](https://user-images.githubusercontent.com/629993/117268458-3f932c00-ae92-11eb-8a17-4123d4cae668.png)
![スクリーンショット 2021-05-06 17 37 44](https://user-images.githubusercontent.com/629993/117268466-415cef80-ae92-11eb-899e-febc0afec047.png)

**Comment by tokorom** [comment]
@psbss @brettins 

If possible, could you tell me the result of hitting your webhook URL directly with curl?
I would like to know if the content of attachments is displayed in Slack with the following command.

```
curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!","attachments":[{"color":"good","author_name":"author","author_icon":"https://secure.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50","fields":[{"title":"GitHub Actions URL","value":"test"}]}]}' https://hooks.slack.com/services/YOUR_WEBHOOK_URL
```

**Comment by brettins** [comment]
Hey @tokorom, I can confirm CURL works because after being unable to debug this package I gave up and started using CURL directly. 

```
    - name: notify of failure
      if: ${{ failure() }}
      run: "curl -X POST -H 'Content-type: application/json' --data \"{ 'attachments': [ { 'color': '#fb1606', 'title': 'CI Build ${{ github.run_number }} - Run Log', 'title_link': '${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}', 'fields': [ { 'title': 'Status', 'value': ':red_circle: Failed'}, { 'title': 'Stage', 'value': 'TEST' }, { 'title': 'Application', 'value': 'Web Client - Story City Web'},  {'title': 'Commit', 'value': '${{ github.sha }}'}, { 'title': 'Build Number', 'value': '${{ github.run_number }}'}]}]}\" ${{ secrets.SLACK_WEBHOOK_URL }}"
    - name: notify of success
      if: ${{ success() }}
      run: "curl -X POST -H 'Content-type: application/json' --data \"{ 'attachments': [ { 'color': 'good', 'title': 'CI Build ${{ github.run_number }} - Run Log', 'title_link': '${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}', 'fields': [ { 'title': 'Status', 'value': ':large_green_circle: Success'                    }, { 'title': 'Stage', 'value': 'TEST' }, { 'title': 'Application', 'value': 'Web Client - Story City Web'}, {'title': 'Commit', 'value': '${{ github.sha}}'}, { 'title': 'Build Number', 'value': '${{ github.run_number }}'}]}]}\" ${{ secrets.SLACK_WEBHOOK_URL }}"
```

![image](https://user-images.githubusercontent.com/5176335/117322755-84e03b00-ae4b-11eb-94d0-098d39de784e.png)

**Comment by tokorom** [comment]
@brettins 

Thank you for the report, the fact that it works with curl is certainly a problem that should be solved in this package.

I haven't figured out the cause yet, as attachments is working fine in my environment, but I'll report back when it's resolved.

**Comment by brettins** [comment]
I'd be happy to help with anything. Any chance the package fails silently if there's a typo or error?

**Comment by tokorom** [comment]
Yes, currently it fails silently if `JSON.parse()` fails for the string passed to attachments.

**Comment by brettins** [comment]
I think that it's possible that for me and the other person there may have been some unseen characters, maybe the wrong type of carriage return, yaml to text issues, something like that, maybe. Where if you copy and paste it from the forum here the issue doesn't appear, but maybe windows to linux or something causes an issue. Probably having the JSON.parse() error out and say it couldn't parse the attachments/blocks would be helpful in case that's what happened here.

**Comment by tokorom** [comment]
Thanks for pointing that out, I'll consider making it so that we can see that the JSON parsing has failed.
