### ISSUE TITLE
Error: Request failed with status 400

### ISSUE THREAD

**Issue by g0pinath** [tokorom/action-slack-incoming-webhook#14]
Issue scenario:

Am using the below code to trap a release and then send a slack notification and am getting error "Error: Request failed with status 400". The notification works for every other event like deployment created, succeeded etc, except for release published. This used to work, and has broken in the 2 months or so. I strongly believe that this is a GITHUB issue as this error doesnt occur if I create a release manually from github portal. When I create a release from github code shown below, the error from slack .
I will open a case with Git and see how it goes and update here.

      - name: Release Published
        if: github.event_name == 'release' && github.event.action == 'released' 
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{env.SLACK_CHANNEL_WEBHOOK}}
          TITLE: ":loudspeaker: *<${{github.event.release.html_url}}|${{github.event.repository.name}} ${{github.event.release.tag_name}}>* is ready for verification testing."
          BODY: "*${{github.event.release.name}} Release Notes*\n${{github.event.release.body}}"
          BUTTON: "Open ${{github.event.release.tag_name}}"
          URL: ${{github.event.release.html_url}}
          FOOTER: ":information_source: *<${{ github.event.repository.html_url }}|${{github.event.repository.name}} repository>*"
        with:
          text: "CHAdminTable Production Released"

Code to create the release. This release creation event triggers the above code to send slack notification and fails. If the release is created manually from GIT, the slack notification comes through just fine.
--------------------------
      - shell: pwsh
        name: Get the app version from chart.yml
        run: |
                $RELEASE_NUMBER = (get-content .\charts\Metricon.ClickHome.AdminTables.Web\Chart.yaml| ConvertFrom-Yaml | Select version).version
                Write-Output "::set-env name=RELEASE_NUMBER::$RELEASE_NUMBER"
                $env:ReleaseNotes | out-file releasenotes.txt
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ env.Password }}
        with:
          tag_name: ${{ env.RELEASE_NUMBER }}
          release_name: ${{ env.RELEASE_NUMBER }}
          body_path: releasenotes.txt
          draft: true
          prerelease: false

#echo "RELEASE_NUMBER=$RELEASE_NUMBER" >> $GITHUB_ENV - this isnt working.
#https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions

**Comment by tokorom** [comment]
@g0pinath 

In order to isolate the problem, could you please try to run just one simple job like the one below in your environment and see if sending a message to Slack works?
Replace `INCOMING_WEBHOOK_URL` with your variables.

When I tried this job in my environment, I received the message `CHAdminTable Production Released` to Slack.

```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: post a message to slack
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.INCOMING_WEBHOOK_URL }}
      with:
        text: "CHAdminTable Production Released"
```

**Comment by g0pinath** [comment]
Yup, this action works beautifully, across all repos for other events like
deployment created, failed, PR etc. Even for release, if the release is
created from GITHUB portal, the slack notification comes through.
Somehow the create release action by GIT is causing this action to fail. I
am already working with an engineer from GITHUB and will keep you posted.

**Comment by tokorom** [comment]
Thanks for the reply. I understand the situation.
I'm relieved to hear that the action-slack-incoming-webhook itself is working fine!

**Comment by venux92** [comment]
@g0pinath did you finally solve this issue?
I have the same issue `400` I create the release with `Lerna` in a Github action then trigger the slack notification, but I always get `400`
